#Image Segmentation
import numpy as np
import cv2
from matplotlib import pyplot as plt
resim = cv2.imread('min.jpg')
resim = cv2.cvtColor(resim, cv2.COLOR_BGR2RGB)
plt.imshow(resim, cmap="gray")
plt.axis('off')
plt.title("Orijinal resim")
plt.show()
gray = cv2.cvtColor(resim, cv2.COLOR_BGR2GRAY)
plt.imshow(gray,cmap="gray")
plt.axis('off')
plt.title("Gri Tonlamalı Resim")
plt.show()
ret, thresh = cv2.threshold(gray, 0, 255,cv2.THRESH_BINARY_INV +cv2.THRESH_OTSU)
plt.imshow(thresh,cmap="gray")
plt.axis('off')
plt.title("Threshold Resim")
plt.show()
kernel = np.ones((3, 3), np.uint8)
closing = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE,kernel, iterations = 15)
bg = cv2.dilate(closing, kernel, iterations = 1)
dist_transform = cv2.distanceTransform(closing, cv2.DIST_L2, 0)
ret, fg = cv2.threshold(dist_transform, 0.02*dist_transform.max(), 255, 0)
plt.imshow(fg,cmap="gray")
plt.axis('off')
plt.title("Parçalanmış Resim")
plt.show()
